export default {
  resorts: [
    {
      id: "1",
      name: "Sierra Nevada",
      country: "Spain",
      coordinates: { latitude: 37.094998, longitude: -3.400295 },
      pistesKm: 110,
      image:
        "https://piste-maps.co.uk/Piste-Maps/France/Evasion-Mont-Blanc-Piste-Map-2019.jpg",
    },
    {
      id: "2",
      name: "St Moritz",
      country: "Switzerland",
      coordinates: { latitude: 46.496666, longitude: 9.831171 },
      pistesKm: 110,
      image:
        "https://piste-maps.co.uk/Piste-Maps/France/Evasion-Mont-Blanc-Piste-Map-2019.jpg",
    },
    {
      id: "3",
      name: "Kitzbühel",
      country: "Austria",
      coordinates: { latitude: 47.443403, longitude: 12.386379 },
      pistesKm: 110,
      image:
        "https://piste-maps.co.uk/Piste-Maps/France/Evasion-Mont-Blanc-Piste-Map-2019.jpg",
    },
    {
      id: "4",
      name: "Les Arcs",
      country: "France",
      coordinates: { latitude: 45.572112, longitude: 6.830978 },
      pistesKm: 110,
      image:
        "https://piste-maps.co.uk/Piste-Maps/France/Evasion-Mont-Blanc-Piste-Map-2019.jpg",
    },
    {
      id: "5",
      name: "Verbier",
      country: "Switzerland",
      coordinates: { latitude: 46.102499, longitude: 7.224822 },
      pistesKm: 110,
      image:
        "https://piste-maps.co.uk/Piste-Maps/France/Evasion-Mont-Blanc-Piste-Map-2019.jpg",
    },
    {
      id: "6",
      name: "Courmayeur",
      country: "Italy",
      coordinates: { latitude: 45.785182, longitude: 6.969118 },
      pistesKm: 110,
      image:
        "https://piste-maps.co.uk/Piste-Maps/France/Evasion-Mont-Blanc-Piste-Map-2019.jpg",
    },
    {
      id: "7",
      name: "St Anton",
      country: "Austria",
      coordinates: { latitude: 47.130184, longitude: 10.266464 },
      pistesKm: 110,
      image:
        "https://piste-maps.co.uk/Piste-Maps/France/Evasion-Mont-Blanc-Piste-Map-2019.jpg",
    },
    {
      id: "8",
      name: "Soldeu",
      country: "Austria",
      coordinates: { latitude: 42.576919, longitude: 1.669188 },
      pistesKm: 110,
      image:
        "https://piste-maps.co.uk/Piste-Maps/France/Evasion-Mont-Blanc-Piste-Map-2019.jpg",
    },
    {
      id: "9",
      name: "Lech",
      country: "Austria",
      coordinates: { latitude: 47.201756, longitude: 10.158906 },
      pistesKm: 110,
      image:
        "https://piste-maps.co.uk/Piste-Maps/France/Evasion-Mont-Blanc-Piste-Map-2019.jpg",
    },
    {
      id: "10",
      name: "Val d'Isere",
      country: "Switzerland",
      coordinates: { latitude: 45.446293, longitude: 6.976911 },
      pistesKm: 110,
      image:
        "https://piste-maps.co.uk/Piste-Maps/France/Evasion-Mont-Blanc-Piste-Map-2019.jpg",
    },
    {
      id: "11",
      name: "Zermat",
      country: "Switzerland",
      coordinates: { latitude: 46.014641, longitude: 7.743496 },
      pistesKm: 110,
      image:
        "https://piste-maps.co.uk/Piste-Maps/France/Evasion-Mont-Blanc-Piste-Map-2019.jpg",
    },
    {
      id: "12",
      name: "Cortina d'Ampezzo",
      country: "Italy",
      coordinates: { latitude: 46.534851, longitude: 12.121703 },
      pistesKm: 110,
      image:
        "https://piste-maps.co.uk/Piste-Maps/France/Evasion-Mont-Blanc-Piste-Map-2019.jpg",
    },
  ],
  instructors: [
    {
      firstName: "Clea",
      lastName: "Schlender",
      resort: "1",
      gender: "female",
      rate: 56,
    },
    {
      firstName: "Federico",
      lastName: "Buchholz",
      resort: "1",
      gender: "male",
      rate: 45,
    },
    {
      firstName: "Yolanda",
      lastName: "Colon",
      resort: "1",
      gender: "female",
      rate: 43,
    },
    {
      firstName: "Abramo",
      lastName: "Martel",
      resort: "1",
      gender: "male",
      rate: 65,
    },
    {
      firstName: "Caio",
      lastName: "Quijada",
      resort: "1",
      gender: "male",
      rate: 60,
    },
    {
      firstName: "Ramon",
      lastName: "Larue",
      resort: "2",
      gender: "male",
      rate: 68,
    },
    {
      firstName: "Gundula",
      lastName: "Pinto",
      resort: "2",
      gender: "male",
      rate: 63,
    },
    {
      firstName: "Tulio",
      lastName: "Freudenberger",
      resort: "2",
      gender: "male",
      rate: 51,
    },
    {
      firstName: "Dan",
      lastName: "Gabler",
      resort: "2",
      gender: "male",
      rate: 56,
    },
    {
      firstName: "Alienor",
      lastName: "Schlosser",
      resort: "2",
      gender: "female",
      rate: 48,
    },
    {
      firstName: "Viola",
      lastName: "Alberici",
      resort: "2",
      gender: "female",
      rate: 64,
    },
    {
      firstName: "Rosario",
      lastName: "Arnoni",
      resort: "3",
      gender: "male",
      rate: 56,
    },
    {
      firstName: "Candelario",
      lastName: "Rosario",
      resort: "3",
      gender: "male",
      rate: 50,
    },
    {
      firstName: "Rudi",
      lastName: "Fini",
      resort: "3",
      gender: "male",
      rate: 70,
    },
    {
      firstName: "Yanick",
      lastName: "Furst",
      resort: "4",
      gender: "male",
      rate: 56,
    },
    {
      firstName: "Amadeo",
      lastName: "Martel",
      resort: "4",
      gender: "male",
      rate: 42,
    },
    {
      firstName: "Severo",
      lastName: "Gerver",
      resort: "4",
      gender: "male",
      rate: 60,
    },
    {
      firstName: "Ilary",
      lastName: "Favre",
      resort: "4",
      gender: "female",
      rate: 51,
    },
    {
      firstName: "Clea",
      lastName: "Schlender",
      resort: "4",
      gender: "female",
      rate: 56,
    },
    {
      firstName: "Federico",
      lastName: "Buchholz",
      resort: "4",
      gender: "male",
      rate: 45,
    },
    {
      firstName: "Yolanda",
      lastName: "Colon",
      resort: "5",
      gender: "female",
      rate: 43,
    },
    {
      firstName: "Abramo",
      lastName: "Martel",
      resort: "5",
      gender: "male",
      rate: 65,
    },
    {
      firstName: "Caio",
      lastName: "Quijada",
      resort: "5",
      gender: "male",
      rate: 60,
    },
    {
      firstName: "Ramon",
      lastName: "Larue",
      resort: "5",
      gender: "male",
      rate: 68,
    },
    {
      firstName: "Gundula",
      lastName: "Pinto",
      resort: "5",
      gender: "male",
      rate: 63,
    },
    {
      firstName: "Tulio",
      lastName: "Freudenberger",
      resort: "6",
      gender: "male",
      rate: 51,
    },
    {
      firstName: "Dan",
      lastName: "Gabler",
      resort: "6",
      gender: "male",
      rate: 56,
    },
    {
      firstName: "Alienor",
      lastName: "Schlosser",
      resort: "6",
      gender: "female",
      rate: 48,
    },
    {
      firstName: "Viola",
      lastName: "Alberici",
      resort: "6",
      gender: "female",
      rate: 64,
    },
    {
      firstName: "Rosario",
      lastName: "Arnoni",
      resort: "6",
      gender: "male",
      rate: 56,
    },
    {
      firstName: "Candelario",
      lastName: "Rosario",
      resort: "6",
      gender: "male",
      rate: 50,
    },
    {
      firstName: "Rudi",
      lastName: "Fini",
      resort: "7",
      gender: "male",
      rate: 70,
    },
    {
      firstName: "Yanick",
      lastName: "Furst",
      resort: "7",
      gender: "male",
      rate: 56,
    },
    {
      firstName: "Amadeo",
      lastName: "Martel",
      resort: "7",
      gender: "male",
      rate: 42,
    },
    {
      firstName: "Severo",
      lastName: "Gerver",
      resort: "7",
      gender: "male",
      rate: 60,
    },
    {
      firstName: "Ilary",
      lastName: "Favre",
      resort: "7",
      gender: "female",
      rate: 51,
    },
    {
      firstName: "Clea",
      lastName: "Schlender",
      resort: "7",
      gender: "female",
      rate: 56,
    },
    {
      firstName: "Federico",
      lastName: "Buchholz",
      resort: "8",
      gender: "male",
      rate: 45,
    },
    {
      firstName: "Yolanda",
      lastName: "Colon",
      resort: "8",
      gender: "female",
      rate: 43,
    },
    {
      firstName: "Abramo",
      lastName: "Martel",
      resort: "8",
      gender: "male",
      rate: 65,
    },
    {
      firstName: "Caio",
      lastName: "Quijada",
      resort: "8",
      gender: "male",
      rate: 60,
    },
    {
      firstName: "Ramon",
      lastName: "Larue",
      resort: "9",
      gender: "male",
      rate: 68,
    },
    {
      firstName: "Gundula",
      lastName: "Pinto",
      resort: "9",
      gender: "male",
      rate: 63,
    },
    {
      firstName: "Tulio",
      lastName: "Freudenberger",
      resort: "9",
      gender: "male",
      rate: 51,
    },
    {
      firstName: "Dan",
      lastName: "Gabler",
      resort: "9",
      gender: "male",
      rate: 56,
    },
    {
      firstName: "Alienor",
      lastName: "Schlosser",
      resort: "10",
      gender: "female",
      rate: 48,
    },
    {
      firstName: "Viola",
      lastName: "Alberici",
      resort: "10",
      gender: "female",
      rate: 64,
    },
    {
      firstName: "Rosario",
      lastName: "Arnoni",
      resort: "10",
      gender: "male",
      rate: 56,
    },
    {
      firstName: "Candelario",
      lastName: "Rosario",
      resort: "10",
      gender: "male",
      rate: 50,
    },
    {
      firstName: "Rudi",
      lastName: "Fini",
      resort: "10",
      gender: "male",
      rate: 70,
    },
    {
      firstName: "Yanick",
      lastName: "Furst",
      resort: "10",
      gender: "male",
      rate: 56,
    },
    {
      firstName: "Amadeo",
      lastName: "Martel",
      resort: "11",
      gender: "male",
      rate: 42,
    },
    {
      firstName: "Severo",
      lastName: "Gerver",
      resort: "11",
      gender: "male",
      rate: 60,
    },
    {
      firstName: "Ilary",
      lastName: "Favre",
      resort: "11",
      gender: "female",
      rate: 51,
    },
    {
      firstName: "Clea",
      lastName: "Schlender",
      resort: "11",
      gender: "female",
      rate: 56,
    },
    {
      firstName: "Federico",
      lastName: "Buchholz",
      resort: "11",
      gender: "male",
      rate: 45,
    },
    {
      firstName: "Yolanda",
      lastName: "Colon",
      resort: "11",
      gender: "female",
      rate: 43,
    },
    {
      firstName: "Abramo",
      lastName: "Martel",
      resort: "11",
      gender: "male",
      rate: 65,
    },
    {
      firstName: "Caio",
      lastName: "Quijada",
      resort: "11",
      gender: "male",
      rate: 60,
    },
    {
      firstName: "Ramon",
      lastName: "Larue",
      resort: "11",
      gender: "male",
      rate: 68,
    },
    {
      firstName: "Gundula",
      lastName: "Pinto",
      resort: "11",
      gender: "male",
      rate: 63,
    },
  ],
};
